[tool.poetry]
name = "semi-bayes-tseries"
version = "0.1.0"
description = ""
authors = ["Tsuyoshi <tsuyoshi.ueno@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
numpyro = "^0.19.0"
prophet = "^1.1.7"
seaborn = "^0.13.2"
matplotlib = "^3.10.6"
matplotlib-fontja = "^1.1.0"
jupyterlab = "^4.4.7"
numpy = "^2.3.3"
scikit-learn = "^1.7.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
